ASP/publishing/publishing/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using publishing.Areas.Identity.Data;
using publishing.Infrastructure;
using publishing.Models;
using publishing.Models.ViewModels;

namespace publishing.Controllers
{
    [Authorize]
    public class BookingsController : Controller
    {
        private readonly PublishingDBContext _context;
        private readonly UserManager<publishingUser> _userManager;
        private readonly IWebHostEnvironment _appEnvironment;

        public BookingsController(PublishingDBContext context, UserManager<publishingUser> userManager, IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _appEnvironment = appEnvironment;
        }

        // GET: Bookings
        [Authorize(Roles ="admin,manager")]
        public async Task<IActionResult> Index(string? status, string? date, DateTime? startDate, DateTime? endDate, int? startNumber, int? endNumber, double? startCost, double? endCost)
        {
            List<Booking> bookings = _context.Bookings.Include(b => b.PrintingHouse).Include(b => b.Employees).ToList();
            FilterController filterController = new FilterController(_context);


            if (status != null && status != "Все") 
            {
               bookings = filterController.GetBookingWithCertainStatus(status,bookings);
            }

            if (startDate != null || endDate != null) 
            {
                bookings = filterController.GetBookingWithSertainDate(date, startDate, endDate, bookings);
            }


            if (startNumber != null || endNumber != null) 
            {
                bookings = filterController.GetBookingWithSertainNumber(startNumber, endNumber, bookings);
            }

            if (startCost != null || endCost != null) 
            { 
                bookings = filterController.GetBookingsWithCertainCost(startCost, endCost, bookings);
            }

            SelectList statuses = new SelectList(new List<string> { "Все", "Ожидание", "Выполняется", "Выполнен" });
            SelectList dates = new SelectList(new List<string> { "Дата приёма", "Дата выполнения" });
            ViewBag.statuses = statuses;
            ViewBag.dates = dates;


            return View(bookings);
        }

        // GET: Bookings/Detail
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Bookings == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.PrintingHouse).Include(b=>b.Employees).Include(b=>b.BookingProducts)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (booking == null)
            {
                return NotFound();
            }

            if (!IsUserBooking(booking.Id))
                return new StatusCodeResult(403);

            var products = (from bp in _context.BookingProducts.Include(bp => bp.Product).Include(bp => bp.Booking) where bp.BookingId == id select bp.Product).ToList();
            if (products == null)
                return NotFound();

            var modelProducts = _context.Products.Include(p => p.Customer).Where(p => products.Contains(p)).ToList();
            if (modelProducts == null)
                return NotFound();

            //var bookingProducts = (from bp in _context.BookingProducts.Include(bp => bp.Product).Include(bp => bp.Booking) where bp.BookingId == id select bp).ToList();
            //_context.Products.Include(p => p.Customer);
            BookingDetailsViewModel model = new BookingDetailsViewModel();
            model.Booking = booking;
            model.BookingProducts = (from bp in _context.BookingProducts.Include(bp => bp.Product).Include(bp => bp.Booking) where bp.BookingId == id select bp).ToList();
            //model.Products = modelProducts;

            return View(model);
        }

        //// GET: Bookings/Create
        //[Authorize(Roles ="customer")]
        //public IActionResult Create()
        //{
        //    ViewData["PrintingHouseId"] = new SelectList(_context.PrintingHouses, "Id", "Name");
        //    return View();
        //}

        //// POST: Bookings/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,Start,End,Status,Cost,PrintingHouseId")] Booking booking)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(booking);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["PrintingHouseId"] = new SelectList(_context.PrintingHouses, "Id", "Name", booking.PrintingHouseId);
        //    return View(booking);
        //}

        // GET: Bookings/Edit/5
        [Authorize(Roles ="manager,admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Bookings == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings.FindAsync(id);
            if (booking == null)
            {
                return NotFound();
            }

            if(booking.Status != "Выполняется")
                return new StatusCodeResult(403);

            ViewData["PrintingHouseId"] = new SelectList(_context.PrintingHouses, "Id", "Name", booking.PrintingHouseId);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Start,End,Status,Cost,PrintingHouseId")] Booking booking)
        {
            if (id != booking.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Customer customer = GetBookingCustomer(id);
                    string subject = $"Изменение в заказе №{id}";
                    string message = $"Уважаемый(-ая) {customer.Name}! Дата выполнения вашего заказа перенесена на {booking.End.Value.ToString("dd/MM/yyyy")}.<br>С уважением, \"Издательство\".";
                    EmailSender emailSender = new EmailSender();
                    emailSender.SendEmail(customer.Email, subject, message);

                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PrintingHouseId"] = new SelectList(_context.PrintingHouses, "Id", "Name", booking.PrintingHouseId);
            return View(booking);
        }

        // GET: Bookings/Delete/5
        [Authorize(Roles ="customer")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Bookings == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.PrintingHouse)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (booking == null)
            {
                return NotFound();
            }

            //var user = await _userManager.GetUserAsync(HttpContext.User);
            //if (!await _userManager.IsInRoleAsync(user, "admin"))
            //{
            //    if (!IsUserBooking(booking.Id, user.Email))
            //        return new StatusCodeResult(403);
            //}


            if (booking.Status != "Ожидание")
                return new StatusCodeResult(403);

            if (!IsUserBooking(booking.Id))
                return new StatusCodeResult(403);

            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Bookings == null)
            {
                return Problem("Entity set 'PublishingDBContext.Bookings'  is null.");
            }
            var booking = await _context.Bookings.FindAsync(id);
            if (booking != null)
            {
                _context.Bookings.Remove(booking);
            }
            
            await _context.SaveChangesAsync();
            //return RedirectToAction(nameof(Index));
            return RedirectToAction("CustomerBookings", "Customers", new { emailCustomer = _userManager.GetUserAsync(HttpContext.User).Result.Email });
        }

        private bool BookingExists(int id)
        {
          return (_context.Bookings?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        [Authorize(Roles ="customer")]
        public async Task<IActionResult> UnpinProduct(int? bookingId, int? productId)
        {
            if (bookingId == null || productId == null)
                return NotFound();

ASP/publishing/publishing/Views/PrintingHouses/Create.cshtml
@model publishing.Models.PrintingHouse

@{
    ViewData["Title"] = "Добавление типографии";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Добавить типографию</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" id="form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="House" class="control-label"></label>
                <input asp-for="House" class="form-control" />
                <span asp-validation-for="House" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label" style="margin-bottom:5px;"></label>
                <textarea asp-for="Description" id="summernote" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку типографий</a>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#summernote').summernote({
                height: 200,
                placeholder: 'Введите дополнительную информацию',
                disableResizeEditor: true
            });
        });

         $('#form').on('submit', function (e) {
                if ($('#summernote').summernote('isEmpty')) {
                    alert('Необходимо ввести дополнительную информацию');
                    e.preventDefault();
                }              
         });
    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ASP/publishing/publishing/Views/PrintingHouses/Delete.cshtml
@model publishing.Models.PrintingHouse

@{
    ViewData["Title"] = "Удаление типографии";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string address = $"{Model.City}, {Model.Street}, {Model.House}";
}

<h1>Удаление типографии</h1>
<script src="https://api-maps.yandex.ru/2.1/?apikey=094078ac-b2f8-43b8-a414-702a2e9f3ea8&lang=ru_RU" type="text/javascript"></script>
<script type="text/javascript">
    function init() {
        var myMap = new ymaps.Map('map', {
            center: [55.74, 37.58],
            zoom: 13,
            controls: []
        });


        var searchControl = new ymaps.control.SearchControl({
            options: {
                provider: 'yandex#search'
            }
        });

        myMap.controls.add(searchControl);

        searchControl.search('@Html.Raw(address)');
    }
    ymaps.ready(init);

</script>

<h3>Вы уверены,что хотите удалить эту типографию?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.House)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.House)
        </dd>
        <dt id="map" style="height:500px; width:100%;"></dt>
        <dt style="margin-bottom:10px; margin-top:10px;">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            <textarea asp-for="Description" id="summernote" class="form-control"></textarea>
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Вернуться к списку типографий</a>
    </form>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#summernote').summernote({
                height: 150,
                disableDragAndDrop: true,
                disableResizeEditor: true
            });
            $('#summernote').summernote('disable');
        });
    </script>
}

ASP/publishing/publishing/Views/PrintingHouses/Details.cshtml
@model publishing.Models.PrintingHouse

@{
    ViewData["Title"] = "Просмотр типографии";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string address = $"{Model.City}, {Model.Street}, {Model.House}";
}

<h1>Информация о типографии</h1>
<script src="https://api-maps.yandex.ru/2.1/?apikey=094078ac-b2f8-43b8-a414-702a2e9f3ea8&lang=ru_RU" type="text/javascript"></script>
<script type="text/javascript">
     function init() {
        var myMap = new ymaps.Map('map', {
        center: [55.74, 37.58],
        zoom: 13,
        controls: []
        });


        var searchControl = new ymaps.control.SearchControl({
        options: {
        provider: 'yandex#search'
        }
        });

        myMap.controls.add(searchControl);

        searchControl.search('@Html.Raw(address)');
     }
    ymaps.ready(init);

</script>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.House)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.House)
        </dd>
        <dt id="map" style="height:500px; width:100%;">
        </dt>
        <dt style="margin-bottom:10px; margin-top:10px;">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            <textarea asp-for="Description" id="summernote" class="form-control"></textarea>
        </dd>
    </dl>
</div>

@*<div id="map" style="height:200px; width:100%"></div>*@

<div class="container p-0" style="height:40px;">
      <div class="row pb-3">
          <div class="col-md-9">
                @{
                    if (Model.Bookings.Count() != 0){<h4>Заказы</h4>}
                else{<h4>Заказы отсутствуют</h4>
                }
            }
        </div>
        <div class="col-md-3 text-end">
            <a asp-action="LinkPrintingHouseWithBooking" asp-route-id="@Model.Id" class="btn btn-info" style="margin-top:5px;">Привязать к заказу</a>
        </div> 
    </div>
 </div>
   
@{
    if (Model.Bookings.Count() != 0)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Bookings.First().Id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Bookings.First().Start)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Bookings.First().End)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Bookings.First().Status)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Bookings.First().Cost)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Bookings.OrderByDescending(b=> b.Id))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Start)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.End)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cost)
                        </td>
                        <td>
                            @if (item.Status == "Выполняется")
                            {
                                <a asp-controller="Bookings" asp-action="Edit" asp-route-id="@item.Id">Изменить</a> 
                                <span>| </span>
                                string namePrintingHouse = $"\"{Model.Name}\"";
                                <a asp-action="UnpinOrder" asp-route-id="@item.Id" onclick="ConfirmAction('Вы подтверждаете открепление типографии @namePrintingHouse от заказа №@item.Id?')">Открепить</a>
                                <span>| </span>
                            }
                            <a asp-controller="Bookings" asp-action="Details" asp-route-id="@item.Id">Подробнее</a>                          
                        </td>
                    </tr>
                }
            </tbody>
        </table>
     }
}
<div>
    @if (User.IsInRole("admin"))
    {
        <a asp-action="Edit" asp-route-id="@Model.Id">Изменение данных о типографии</a>
        <span>| </span>
    }
    <a asp-action="Index">Вернуться к списку типографий</a>
</div>


@section Scripts {
    <script>
        $(document).ready(function() {
        $('#summernote').summernote({
            height:150,
            disableDragAndDrop: true,
            disableResizeEditor: true
        });
            $('#summernote').summernote('disable');
        });
    </script>
}

ASP/publishing/publishing/Views/PrintingHouses/Edit.cshtml
@model publishing.Models.PrintingHouse

@{
    ViewData["Title"] = "Изменение данных о типографии";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Изменение данных о типографии</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" id="form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="House" class="control-label"></label>
                <input asp-for="House" class="form-control" />
                <span asp-validation-for="House" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label" style="margin-bottom:5px;"></label>
                <textarea asp-for="Description" id="summernote" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Изменить" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку типографий</a>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#summernote').summernote({
                height: 200,
                placeholder: 'Введите дополнительную информацию',
                disableResizeEditor: true
            });
        });

        $('#form').on('submit', function (e) {
            if ($('#summernote').summernote('isEmpty')) {
                alert('Необходимо ввести дополнительную информацию о сотруднике');
                e.preventDefault();
            }
        });

    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ASP/publishing/publishing/Views/PrintingHouses/LinkPrintingHouseWithBooking.cshtml
@model IEnumerable<publishing.Models.Booking>

@{
    ViewData["Title"] = "Привязка к заказу";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Привязка к заказу</h1>
<form method="post" class="form-group" onsubmit="CheckBoxes('Пожалуйста, выберите заказ(-ы) для привязки к типографии')">
    @{
        if (Model.Count() != 0)
        {
            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>
                            Выбрать
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Start)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.End)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Status)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Cost)
                        </th>
                        <th>Информация о заказе</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.OrderByDescending(m=> m.Id))
                    {
                        <tr>
                            <td>
                                <input type="checkbox" class="check_box" name="selectedBookings" id="@item.Id" value="@item.Id">
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Start)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.End)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Cost)
                            </td>
                            <td style="width:250px;">
                                <a asp-controller="Bookings" asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Подробнее</a>
                                <input type="hidden" name="printHouseId" value="@ViewBag.printHouseId">
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="form-group pt-3" style="margin-top: -15px;">
                <input type="submit" value="Привязать" class="btn btn-success" />
            </div>
        }
        else
        {
            <h4 style ="margin-top:7px;">Заказы отсутствуют</h4>    
        }
    }
</form>