ASP/publishing/publishing/Models/Customer.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace publishing.Models
{
    public class Customer
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Введите наименование заказчика")]
        [DataType(DataType.Text)]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "Длина строки не входит в заданный диапазон:[1,50]")]
        [DisplayName("Наименование заказчика")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Введите номер телефона")]
        [DataType(DataType.PhoneNumber)]
        [DisplayName("Номер телефона")]
        [RegularExpression(@"\+7-\d{3}-\d{3}-\d{2}-\d{2}", ErrorMessage ="Неверный номер телефона.Паттерн: +7-###-###-##-##")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "Введите электронную почту")]
        [DataType(DataType.EmailAddress)]
        [DisplayName("Электронная почта")]
        [MaxLength(50)]
        [RegularExpression(@"[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}", ErrorMessage ="Введена неверная электронная почта")]
        public string Email { get; set; }

        public virtual ICollection<Product> Products { get; set; }

        public Customer()
        {
            Products = new List<Product>();
        }

        public Customer(string name, string phone, string email)
        {
            Name = name;
            Phone = phone;
            Email = email;
            Products = new List<Product>();
        }
    }
}

ASP/publishing/publishing/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using publishing.Areas.Identity.Data;
using publishing.Models;
using publishing.Models.ViewModels;
using publishing.Infrastructure;
using OfficeOpenXml;
using System.IO.Pipelines;
using Microsoft.IdentityModel.Tokens;
using System.Data;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace publishing.Controllers
{
    [Authorize]
    public class CustomersController : Controller
    {
        private readonly PublishingDBContext _context;
        private readonly UserManager<publishingUser> _userManager;
        private readonly IWebHostEnvironment _appEnvironment;

        public CustomersController(PublishingDBContext context, UserManager<publishingUser> userManager, IWebHostEnvironment appEnvironment)
        {
            _context = context;
            _userManager = userManager;
            _appEnvironment = appEnvironment;
        }

        // GET: Customers
        [Authorize(Roles = "manager,admin")]
        public IActionResult Index(string? name, string? phoneNumber, string? email)
        {
            List<Customer> customers = _context.Customers.ToList();

            if (name != null)
                customers = customers.Where(c => c.Name == name).ToList();

            if(phoneNumber != null)
                customers = customers.Where(c => c.Phone == phoneNumber).ToList();

            if (email != null)
                customers = customers.Where(c => c.Email == email).ToList();

            return View(customers);
        }

        // GET: Customers/Details/5
        [Authorize(Roles = "manager,admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Customers == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.Include(c => c.Products)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (customer == null)
            {
                return NotFound();
            }

            CustomerDetailsViewModel model = new CustomerDetailsViewModel();
            model.Customer = customer;

            //var products = _context.Products.Include(p => p.TypeProduct).Where(p => customer.Products.Contains(p)).ToList();
            //if(products == null)
            //    return NotFound();

            model.Bookings = GetBookings(customer);
            model.Products = GetProducts(customer,true);
            //model.Bookings.AddRange(from bp in _context.BookingProducts.Include(bp => bp.Booking).Include(bp => bp.Product) where products.Contains(bp.Product) && !model.Bookings.Contains(bp.Booking) && bp.Booking != null select bp.Booking);
            //model.Products.AddRange((from bp in _context.BookingProducts.Include(bp => bp.Product) where products.Contains(bp.Product) && bp.Booking != null select bp.Product).Distinct());

            //foreach (var product in products)
            //{
            //    model.Bookings.AddRange(from bp in _context.BookingProducts.Include(bp => bp.Booking) where bp.ProductId == product.Id && !model.Bookings.Contains(bp.Booking) && bp.Booking != null select bp.Booking);
            //    model.Products.AddRange((from bp in _context.BookingProducts.Include(bp => bp.Product) where bp.ProductId == product.Id && bp.Booking != null select bp.Product).Distinct());
            //}

            return View(model);
        }

        //// GET: Customers/Create
        //[Authorize(Roles = "admin")]
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Customers/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,Name,Phone,Email")] Customer customer)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(customer);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(customer);
        //}

        //// GET: Customers/Edit/5
        //[Authorize(Roles = "admin")]
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null || _context.Customers == null)
        //    {
        //        return NotFound();
        //    }

        //    var customer = await _context.Customers.FindAsync(id);
        //    if (customer == null)
        //    {
        //        return NotFound();
        //    }
        //    return View(customer);
        //}

        //// POST: Customers/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Phone,Email")] Customer customer)
        //{
        //    if (id != customer.Id)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(customer);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!CustomerExists(customer.Id))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    return View(customer);
        //}

        //// GET: Customers/Delete/5
        //[Authorize(Roles = "admin")]
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null || _context.Customers == null)
        //    {
        //        return NotFound();
        //    }

        //    var customer = await _context.Customers
        //        .FirstOrDefaultAsync(m => m.Id == id);
        //    if (customer == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(customer);
        //}

        //// POST: Customers/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    if (_context.Customers == null)
        //    {
        //        return Problem("Entity set 'PublishingDBContext.Customers'  is null.");
        //    }
        //    var customer = await _context.Customers.FindAsync(id);
        //    if (customer != null)
        //    {
        //        _context.Customers.Remove(customer);
        //    }

        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool CustomerExists(int id)
        {
            return (_context.Customers?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private List<Booking> GetBookings(Customer customer)
        {
            List<Booking> bookings = new List<Booking>();
            var customerProducts = _context.Products.Include(p => p.TypeProduct).Where(p => customer.Products.Contains(p)).ToList();
            if (customerProducts != null)
            {
                bookings.AddRange((from bp in _context.BookingProducts.Include(bp => bp.Booking).Include(bp => bp.Product) where customerProducts.Contains(bp.Product) && bp.Booking != null select bp.Booking).Distinct());
            }

            return bookings;
        }

        private List<Product> GetProducts(Customer customer,bool InBooking)
        {
            List<Product> products = new List<Product>();
            var customerProducts = _context.Products.Include(p => p.TypeProduct).Include(p=>p.BookingProducts).ThenInclude(bp=>bp.Booking).Where(p => customer.Products.Contains(p)).ToList();
            if (customerProducts != null)
            {
                if (InBooking)
                    products.AddRange((from bp in _context.BookingProducts.Include(bp => bp.Product) where customerProducts.Contains(bp.Product) && bp.Booking != null select bp.Product).Distinct());

                else
                    products = customerProducts;
            }
            return products;
        }

        [Authorize(Roles = "customer")]
        public async Task<IActionResult> CustomerBookings(string emailCustomer, string? status, string? date, DateTime? startDate, DateTime? endDate, int? startNumber, int? endNumber, double? startCost, double? endCost)
        {
            var customer = _context.Customers.Include(c => c.Products).FirstOrDefault(c => c.Email == emailCustomer);
            if (customer == null)
                return NotFound();

            if (!IsCustomerEmail(emailCustomer))
                return new StatusCodeResult(403);


            List<Booking> bookings = GetBookings(customer);
            FilterController filterController = new FilterController(_context);


            if (status != null && status != "Все")
            {
                bookings = filterController.GetBookingWithCertainStatus(status, bookings);
            }

            if (startDate != null || endDate != null)
            {
                bookings = filterController.GetBookingWithSertainDate(date, startDate, endDate, bookings);
            }

ASP/publishing/publishing/Views/Customers/Create.cshtml
@model publishing.Models.Customer

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Добавить заказчика</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Добавить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку заказчиков</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ASP/publishing/publishing/Views/Customers/CustomerBookings.cshtml
@model IEnumerable<publishing.Models.Booking>
@using Microsoft.AspNetCore.Identity
@using publishing.Areas.Identity.Data

@inject UserManager<publishingUser> UserManager

@{
    ViewData["Title"] = "Список заказов";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userName = UserManager.GetUserAsync(User).Result.Email;
}

<h1>Список заказов</h1>

<div style="display:inline"></div>
<p>
    <a asp-action="TransitionToSelectProducts" asp-route-bookingId="-1">Создать заказ</a>
    @if (Model.Where(m=>m.Status == "Выполнен").Count() > 0)
    {
        <span>| </span>
        <a asp-controller="Bookings" asp-action="GetReportAboutCompletedBookings">Отчёт о выполненных заказах</a>
        <span>| </span>
        <a asp-controller="Bookings" asp-action="GetReportAboutCostCompletedBookings">Отчёт о расходах</a>
    }
</p>
@{
    if (Model.Count() > 0)
    {
        <div class="info">
            <input id="info__body_1" class="info__switch" type="checkbox">
            <label for="info__body_1" class="info__headline">Фильтрация данных</label>
            <div class="info__body">
                <form method="get" asp-action="CustomerBookings" onsubmit="CheckDifferenceBetweenStartEndDates(); CheckDifferenceBetween2Numbers('startNumber', 'endNumber'); CheckDifferenceBetween2Numbers('startCost','endCost')">
                <input type="hidden" name="emailCustomer" value="@userName">
                    <div class="d-flex">
                        <div class="d-inline-block">
                            <label>Стасус: </label>
                        </div>
                        <div class="d-inline-block" style="margin-left:7px;">
                            <select class="form-control form-select" name="status" asp-items="@ViewBag.statuses"></select>
                        </div>
                        <div class="d-inline-block" style="margin-left:10px;">
                            <label>Дата: </label>
                        </div>
                        <div class="d-inline-block" style="margin-left:7px;">
                            <select class="form-control form-select" name="date" asp-items="@ViewBag.dates"></select>
                        </div>
                        <div class="d-inline-block" style="margin-left:10px;">
                            <label>С: </label>
                        </div>
                        <div class="d-inline-block" style="margin-left:7px;">
                            <input type="date" name="startDate" id="datefield" class="form-control" min="2000-01-02" style="width:214px;" />
                        </div>
                        <div class="d-inline-block" style="margin-left:10px;">
                            <label>По: </label>
                        </div>
                        <div class="d-inline-block" style="margin-left:7px;">
                            <input type="date" name="endDate" id="endfield" class="form-control" min="2000-01-02" max="2100-01-01" style="width:214px;" />
                        </div>
                        <div class="d-inline-block" style="margin-left:10px;">
                            <input type="submit" value="Поиск" class="btn btn-primary" style="margin-top:5px;width:200px;" />
                        </div>
                    </div>

                    <div class="d-flex" style="margin-top:5px;">
                        <div class="d-inline-block">
                            <label>Номер заказа: </label>
                        </div>
                        <div class="d-inline-block" style="margin-left:7px;">
                            <label>С: </label>
                        </div>
                        <div class="d-inline-block" style="margin-left:7px;">
                            <input type="number" class="form-control" name="startNumber" id="startNumber" min="1" max="10000000" oninput="this.value = Math.round(this.value);">
                        </div>
                        <div class="d-inline-block" style="margin-left:10px;">
                            <label>По: </label>
                        </div>
                        <div class="d-inline-block" style="margin-left:7px;">
                            <input type="number" class="form-control" name="endNumber" id="endNumber" min="2" max="10000000" oninput="this.value = Math.round(this.value);">
                        </div>

                        <div class="d-inline-block" style="margin-left:10px;">
                            <label>Стоимость заказа: </label>
                        </div>
                        <div class="d-inline-block" style="margin-left:7px;">
                            <label>С: </label>
                        </div>
                        <div class="d-inline-block" style="margin-left:7px;">
                            <input type="number" class="form-control" id="startCost" name="startCost" min="1.00" max="10000000">
                        </div>
                        <div class="d-inline-block" style="margin-left:10px;">
                            <label>По: </label>
                        </div>
                        <div class="d-inline-block" style="margin-left:7px;">
                            <input type="number" class="form-control" id="endCost" name="endCost" min="1.00" max="10000000">
                        </div>
                        <div class="d-inline-block" style="margin-left:10px;">
                            <a asp-action="CustomerBookings" asp-route-emailCustomer="@userName" class="btn btn-primary" style="margin-top:5px; width:200px;">Сброс</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>


        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Start)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.End)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Status)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Cost)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.OrderByDescending(m => m.Id))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Start)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.End)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Cost)
                        </td>
                        <td>
                            @if (item.Status == "Ожидание")
                            {
                                <a asp-controller="Customers" asp-action="TransitionToSelectProducts" asp-route-bookingId="@item.Id">Изменить</a>
                                <span>| </span>
                                <a asp-controller="Bookings" asp-action="Delete" asp-route-id="@item.Id">Удалить</a> 
                                <span>| </span>
                            }
                            <a asp-controller="Bookings" asp-action="Details" asp-route-id="@item.Id">Подробнее</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
}

ASP/publishing/publishing/Views/Customers/CustomerProducts.cshtml
@model IEnumerable<publishing.Models.Product>
@using Microsoft.AspNetCore.Identity
@using publishing.Areas.Identity.Data

@inject UserManager<publishingUser> UserManager

@{
    ViewData["Title"] = "Список продукций";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userName = UserManager.GetUserAsync(User).Result.Email;
}

<h1>Список продукций</h1>

<p>
    <a asp-controller = "Products" asp-action="Create">Добавить продукцию</a>
</p>


@if (Model.Count() > 0)
{
    <div class="info">
        <input id="info__body_1" class="info__switch" type="checkbox">
        <label for="info__body_1" class="info__headline">Фильтрация данных</label>
        <div class="info__body">
            <form method="get" asp-action="CustomerProducts" onsubmit="CheckDifferenceBetween2Numbers('startCost','endCost')">
                <input type="hidden" name="emailCustomer" value="@userName">

                <div class="d-flex">
                    <div class="d-inline-block">
                        <label>Название: </label>
                    </div>
                    <div class="d-inline-block" style="margin-left:7px;">
                        <input type="text" class="form-control" name="name">
                    </div>
                    <div class="d-inline-block" style="margin-left:10px;">
                        <label>Тип: </label>
                    </div>
                    <div class="d-inline-block" style="margin-left:7px;">
                        <input type="text" name="type" class="form-control">
                    </div>
                    <div class="d-inline-block" style="margin-left:10px;">
                        <input type="submit" value="Поиск" class="btn btn-primary" style="margin-top:5px; width:230px;" />
                    </div>
                </div>

                <div class="d-flex" style="margin-top:5px;">
                    <div class="d-inline-block">
                        <label>Стоимость: </label>
                    </div>
                    <div class="d-inline-block" style="margin-left:7px;">
                        <label>С: </label>
                    </div>
                    <div class="d-inline-block" style="margin-left:7px;">
                        <input type="number" class="form-control" id="startCost" name="startCost" min="1.00" max="10000000" style="width:195px;">
                    </div>
                    <div class="d-inline-block" style="margin-left:10px;">
                        <label>По: </label>
                    </div>
                    <div class="d-inline-block" style="margin-left:7px;">
                        <input type="number" class="form-control" id="endCost" name="endCost" min="1.00" max="10000000" style="width:196px;">
                    </div>
                    <div class="d-inline-block" style="margin-left:10px;">
                        <a asp-action="CustomerProducts" asp-route-emailCustomer="@userName" class="btn btn-primary" style="margin-top:5px; width:230px;">Сброс</a>
                    </div>
                </div>
            </form>
        </div>
    </div>


    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cost)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TypeProduct.Type)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.OrderBy(m => m.Name))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cost)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TypeProduct.Type)
                    </td>
                    <td>
                        @if (!item.BookingProducts.Any(bp => bp.Booking.Status != "Ожидание"))
                        {
                            <a asp-controller="Products" asp-action="Edit" asp-route-id="@item.Id">Изменить</a>
                            <span>| </span>
                            <a asp-controller="Products" asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
                            <span>| </span>
                        }
                        <a asp-controller="Products" asp-action="Details" asp-route-id="@item.Id">Подробнее</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

ASP/publishing/publishing/Views/Customers/Delete.cshtml
@model publishing.Models.Customer

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Удаление заказчика</h1>

<h3>Вы уверены,что хотите удалить этого заказчика?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Удалить" class="btn btn-danger" /> |
        <a asp-action="Index">Вернуться к списку заказчиков</a>
    </form>
</div>

ASP/publishing/publishing/Views/Customers/Edit.cshtml
@model publishing.Models.Customer


@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Изменение данных о заказчике</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Изменить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Вернуться к списку заказчиков</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}